name: platform_ci_dev_workflow

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      use_case_base_path:
        type: string
        description: "The flow use-case to execute"
        required: true
        default: "math_coding"
  workflow_dispatch:
    inputs:
      env_name:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      use_case_base_path:
        type: string
        description: "The flow use-case to execute"
        required: true
        default: "math_coding"
jobs:
  flow-experiment-and_evaluation:
    name: prompt flow experiment and evaluation job
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env_name }}
    env:
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      WORKSPACE_NAME: ${{ vars.PROJECT_NAME }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .github/requirements/execute_job_requirements.txt
          python -m pip install .github/workflows/azure_ai_projects-1.0.0b1-py3-none-any.whl --user --force-reinstall


      - name: Create .env file
        env: 
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > .env
          python -c "from dotenv import load_dotenv; load_dotenv()"
          echo "Created .env file with all secrets"

      - name: load .env file
        run: python -c "from dotenv import load_dotenv; load_dotenv()"

      - name: load the current Azure subscription details
        id: subscription_details
        shell: bash
        run: |
          export subscriptionId=$(az account show --query id -o tsv)
          echo "SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_OUTPUT

      #=====================================
      # Executes Standard flow for a scenario
      # Generates Reports for each RUN as well as consolidated one
      # Execute a RUN for each unique variant combination (keeping default variant id for other nodes)
      # Loads appropriate experiment data from Azure ML data asset
      # Reads appropriate field values from experiment.yaml or experiment.<env>.yaml
      # Prompt Flow connections should pre-exist 
      # used automatic (serverless) runtime by default
      # writes the RUN ID in run_id.txt file. Used in next step
      #=====================================
      - name: Execute prompt flow bulk run
        uses: ./.github/actions/execute_script
        with:
          step_name: "Execute prompt flow bulk run"
          script_parameter: |
            python -m llmops.eval_experiments \
            --environment_name ${{ inputs.env_name }} \
            --base_path ${{ inputs.use_case_base_path }} \
            --report_dir "."

